apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: development
  labels:
    app: hello
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001
      protocol: TCP
  selector:
    app: hello

