apiVersion: v1
kind: Service
metadata:
  name: app2-svc
  namespace: development
  labels:
    app: app2
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30002
      protocol: TCP
  selector:
    app: app2

