apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: development
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      type: mysql
  template:
    metadata:
      labels:
        type: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: TZ
            value: Europe/Rome
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-config
                key: mysql_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-1
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-1
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
